# 开发环境配置
services:
  openhands:
    environment:
      # 开发环境特定配置
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - DISABLE_COLOR=false
      - SECURITY_CONFIRMATION_MODE=true
    volumes:
      # 开发时的额外挂载
      - ./dev-workspace:/workspace
      - ./dev-config.toml:/app/config.toml:ro
    ports:
      # 额外的调试端口
      - "3000:3000"
      - "8000:8000"  # 调试端口
    labels:
      - "com.openhands.env=development"

  # 开发工具容器
  dev-tools:
    image: alpine:latest
    container_name: openhands-dev-tools
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - openhands-network
    profiles:
      - dev-tools